version: '3.7'
services:
    django:
        build: ./backend
        env_file:
            - ./.env
        command: python manage.py runserver 0.0.0.0:8081
        ports:
            - "8081:8081"
        depends_on:
            - db
    angular-prod:
        container_name: angular-prod
        env_file:
            - ./.env
        build:
            context: ./
            dockerfile: Dockerfile-prod
        ports:
            - '80:80'
        depends_on:
            - django
    db:
        image: postgres
volumes:
  data-volume: